version: '3.8'

services:
  unifi-protect:
    image: ghcr.io/kiwimato/unifi-protect-arm64:dev
    container_name: unifi-protect
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ${PWD}/storage/unifi-protect/srv:/srv
      - ${PWD}/storage/unifi-protect/data:/data
      - ${PWD}/storage/unifi-protect/storage/persistent:/persistent
    environment:
      - STORAGE_DISK=/dev/sdb1
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    cap_add:
      - dac_read_search
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/run/lock
    privileged: true
    network_mode: host
